source_dict = {
    "afg": "agcho",
    "ago": "ine",
    "aia": "gdam",
    "alb": "unhcr",
    "and": "no cod data",
    "are": "uaemca",
    "arg": "unhcr",
    "arm": "ga",
    "atg": "gadm",
    "aus": "no cod data",
    "aut": "no cod data",
    "aze": "gadm",
    "bdi": "igebu",
    "bel": "no cod data",
    "ben": "ocha",
    "bfa": "igb",
    "bgd": "bbs",
    "bgr": "unicef",
    "bhr": "wfp",
    "bhs": "gadm",
    "bih": "osm",
    "blr": "unicef",
    "blz": "gadm",
    "bmu": "gadm",
    "bol": "geobol",
    "bra": "ibge",
    "brb": "gadm",
    "brn": "no cod data",
    "btn": "ocha",
    "bwa": "unfrpa",
    "caf": "acted",
    "can": "no cod data",
    "che": "no cod data",
    "chi": "bcn",
    "chl": "bcn",
    "chn": "roap",
    "civ": "cntig",
    "cmr": "osm",
    "cod": "rgc",
    "cog": "gaul",
    "cok": "no cod data",
    "col": "dane",
    "com": "cosep",
    "cpv": "salb",
    "cri": "nso",
    "cub": "gadm",
    "cym": "gadm",
    "cyp": "no cod data",
    "cze": "no cod data",
    "deu": "no cod data",
    "dji": "gadm",
    "dma": "ocha",
    "dnk": "no cod data",
    "dom": "onde",
    "dza": "unhcr",
    "ecu": "inec",
    "egy": "capmas",
    "eri": "ocha",
    "esp": "no cod data",
    "est": "no cod data",
    "eth": "bofed",
    "fin": "no cod data",
    "fji": "pcrafi",
    "flk": "no cod data",
    "fra": "no cod data",
    "fro": "no cod data",
    "fsm": "fsmds",
    "gab": "salb",
    "gbr": "no cod data",
    "geo": "nsog",
    "ggy": "no cod data",
    "gha": "gss",
    "gib": "no cod data",
    "gin": "wfp",
    "gmb": "ndma",
    "gnb": "salb",
    "gnq": "gadm",
    "grc": "eurogeographics",
    "grd": "gadm",
    "grl": "no cod data",
    "gtm": "cnprd",
    "guy": "dlp",
    "hnd": "seplan",
    "hrv": "no cod data",
    "hti": "cnigs",
    "hun": "osm",
    "idn": "bps",
    "imn": "no cod data",
    "ind": "no cod data",
    "iot": "no cod data",
    "irl": "no cod data",
    "irn": "unhcr",
    "irq": "icso",
    "isl": "no cod data",
    "isr": "no cod data",
    "ita": "no cod data",
    "jam": "gadm",
    "jey": "no cod data",
    "jor": "no cod data",
    "jpn": "ocha",
    "kaz": "unhcr",
    "ken": "iebc",
    "kgz": "meskr",
    "khm": "wfp",
    "kir": "spcsdd",
    "kna": "gadm",
    "kor": "no cod data",
    "kwt": "gadm",
    "lao": "ngd",
    "lbn": "cdr",
    "lbr": "unmil",
    "lby": "iom",
    "lca": "dpp",
    "lie": "no cod data",
    "lka": "sdsl",
    "lso": "fmlg",
    "ltu": "no cod data",
    "lux": "no cod data",
    "lva": "no cod data",
    "mar": "hcp",
    "mco": "no cod data",
    "mda": "unhcr",
    "mdg": "bngrc",
    "mdv": "grm",
    "mex": "inegi",
    "mhl": "spcsdd",
    "mkd": "ntus",
    "mli": "dnct",
    "mlt": "no cod data",
    "mmr": "mimu",
    "mne": "no cod data",
    "mng": "nsom",
    "moz": "ine",
    "mrt": "ansade",
    "msr": "gadm",
    "mus": "sm",
    "mwi": "nsom",
    "mys": "unhcr",
    "nam": "nsa",
    "ner": "ignn",
    "nga": "uncs",
    "nic": "gadm",
    "niu": "no cod data",
    "nld": "no cod data",
    "nor": "no cod data",
    "npl": "sdn",
    "nru": "no cod data",
    "nzl": "no cod data",
    "omn": "gadm",
    "pak": "wfp",
    "pan": "gdam",
    "pcn": "no cod data",
    "per": "ign",
    "phl": "psa",
    "plw": "no cod data",
    "png": "pngnso",
    "pol": "prg",
    "prk": "wfp",
    "prt": "no cod data",
    "pry": "dgeec",
    "qat": "qpsa",
    "rou": "ancpi",
    "rus": "gadm",
    "rwa": "nisr",
    "sau": "gadm",
    "sdn": "imwg",
    "sen": "gs",
    "sgp": "no cod data",
    "sgs": "no cod data",
    "shn": "no cod data",
    "slb": "sinso",
    "sle": "gsl",
    "slv": "gadm",
    "smr": "no cod data",
    "som": "ocha",
    "srb": "no cod data",
    "ssd": "imwg",
    "stp": "gadm",
    "sur": "gadm",
    "svk": "geoportal",
    "svn": "no cod data",
    "swe": "no cod data",
    "swz": "cso",
    "syc": "snbs",
    "syr": "unocha",
    "tca": "gadm",
    "tcd": "inseedt",
    "tgo": "gaul",
    "tha": "rtsd",
    "tjk": "asprt",
    "tkl": "no cod data",
    "tkm": "no cod data",
    "tls": "who",
    "ton": "spcsdddl",
    "tto": "gadm",
    "tun": "inst",
    "tur": "gcm",
    "tuv": "no cod data",
    "twn": "no cod data",
    "tza": "tnbs",
    "uga": "ubs",
    "ukr": "sspec",
    "ury": "gadm",
    "usa": "no cod data",
    "uzb": "ocha",
    "vat": "no cod data",
    "vct": "gadm",
    "ven": "ine",
    "vgb": "gadm",
    "vnm": "gvn",
    "vut": "spc",
    "wsm": "no cod data",
    "xkx": "no cod data",
    "yem": "cso",
    "zaf": "samdb",
    "zmb": "dmmu",
    "zwe": "zimstat"
}